### ISSUE TITLE
Bump new version?

### ISSUE THREAD

**Issue by bcho** [sjansen/watchman#20]
Hey thanks for providing this go binding to watchman. I noticed that last 0.1.0 release was 4 yrs ago. Can we create a new release to the main branch to publish the latest change? Otherwise, go get will retrieve the very old 0.1.0 release.

**Comment by sjansen** [comment]
Thank you for showing interest!

Although tests are passing, one of the examples is failing. I would like to make sure it is fixed before cutting a new release.

I'll try to do so in the next few days, but can't commit to anything. Of course PRs are welcome. 😉

**Comment by bcho** [comment]
Do you mean the simple-watcher? I ran into this error from local:

```
watchman::RootResolveError: RootResolveError: unable to resolve root /<path>/watchman/examples/simple-watcher: RootResolveError: directory /<path>/watchman/examples/simple-watcher is not watched
```

**Comment by sjansen** [comment]
I just pushed a new release and tested it by creating a trivial new project.

Let me know if you see any issues.

**Comment by bcho** [comment]
Thank you!
